### ISSUE TITLE
Depracte .lsdfnt?

### ISSUE THREAD

**Issue by Eiyeron** [Eiyeron/lsdpatch#24]
I'm starting to wonder as now that we can easily import/export fonts as fonts, wouldn't it be good to deprecate .lsdfnts and remove them later?

(Hey @jkotlinski, I'd like your advice on the question, as it's your software after all.)

**Comment by jkotlinski** [comment]
How about keeping the loading of .lsdfnt files and removing the saving?

A thought about the .png dimensions. Maybe it would be practical to put all characters on a single row? That would make it a little easier to create a nice table. If you for example look at the one in https://github.com/urbster1/lsdfonts , it could be a table with 2 columns (name on the left, image on the right), and formatting would be less messed up.

**Comment by jkotlinski** [comment]
On the other hand, I guess quadratic .png size is nicer when previewing in Finder/Explorer.

**Comment by Eiyeron** [comment]
Hey there. Sorry for the delayed reply. But yeah, the idea of offering different layouts for the fonts isn't a  bad one. I'm currently thinking on how to make the IO more flexible (checking/clamping image sizes and all) and will probably make a project ticket for it.

For the deprecation, that's almost what I had in mind. I had in mind a nagging popup on .lsdfnt saving that would tell that the file format is deprecated. At least I'm glad we seem to agree on the question. That'll be another task for the 2.0. Thanks for the reply

**Comment by Eiyeron** [comment]
Due to the fork's new direction, I'll deprecate the format. Most fonts I have seen are on the [font repository][fnt]. I almsot see no traces of lsdfnts anymore. Eventually, I'll keep at least an import function the saving function is planned to be removed for 2.0

[fnt]: https://github.com/psgcabal/lsdfonts
