### ISSUE TITLE
Strange antialiasing on UI text

### ISSUE THREAD

**Issue by jkotlinski** [Eiyeron/lsdpatch#47]
Hi, when running the app on Windows, there is some antialiasing applied to all text elements that look strange. Not a deal breaker but I thought I should let you know!

**Comment by jkotlinski** [comment]
![bild](https://user-images.githubusercontent.com/3259963/74198644-3cdf6200-4c62-11ea-83df-b34939c82bc7.png)

**Comment by Eiyeron** [comment]
Hello. I tried to use the system Look&Feel to make the patcher look more like a native program. and tried to enable text antialiasing, hoping it'd use ClearType on Windows, which it definitely doesn't on the menus. I'll check if I can tweak that or if I should just remove it.

**Comment by Eiyeron** [comment]
Closed, thanks for the report!

**Comment by jkotlinski** [comment]
Hi again, it seems this problem is fixed in newer JRE versions. So it was nothing to worry about on "our" side I guess :-P
