### ISSUE TITLE
Bug: Command-line font patching does not replace entire font

### ISSUE THREAD

**Issue by urbster1** [Eiyeron/lsdpatch#48]
See example screenshot
`java -jar lsdpatch-redux-1.4.3.jar png2romfnt gb\lsdj815fmdumb.gb lsdfonts\png\boom.png 1 boom`
The new font does not entirely replace the old font. However, using the GUI works as expected.
![image](https://user-images.githubusercontent.com/5685593/74695871-8e886f00-51c3-11ea-8f08-0bbfb9bce4e3.png)

**Comment by Eiyeron** [comment]
Ok, sorry for the inconvenience, I'll have a look.

**Comment by Eiyeron** [comment]
Ok, I see the issue and potentially a new feature: LSDJ stores fonts in three variant:
- colored normally
- inverted colors
- shaded colors

This exactly makes us three copies of the same font. I forgot to call the function to regenerate the other variants on the command line function.

But also this opens up to a neat idea: why not leaving the ability for the user to tweak the three font variants individually?
